# Generated by Django 2.2 on 2020-04-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200419_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatDo',
            new_name='WhatToDo',
        ),
    ]
